### ISSUE TITLE
我觉得这个游戏真的好有趣，博主，如果我想要学习您的这个项目，有哪些基础知识需要补充呢？

### ISSUE THREAD

**Issue by shijianzugouniai** [pengfeiw/vue-hextris#4]

**Comment by pengfeiw** [comment]
游戏用到的技术： ts + canvas + vue。

假设你没有任何基础的情况下，我推荐一些相关的知识和教程：
- [html](https://wangdoc.com/html/)
- [css](https://pengfeixc.com/css-tutorial)
- [javascript](https://wangdoc.com/javascript/)
- [canvas 2d 绘图](https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Basic_usage)

上面的知识完全可以实现一些画布游戏。如果想进阶学习，在看看下面的。

一般学了javascript，还需要学习 es6 和 typescript：
- [es6](https://wangdoc.com/es6)
- [ts handbook](https://www.typescriptlang.org/docs/handbook/intro.html)

既然已经学了这么多了，不防选择一个 web 框架，vue 或者 react，这两个推荐看官方文档即可。

其实这个游戏用到的都是开发一般网页用到的技术，除了 canvas 是属于图形领域的技术。

**Comment by shijianzugouniai** [comment]
考试结束了，终于暑假有时间来学习博主您的项目了，对vue有一些初步理解，其他相关的技术可以边做边学吗？感谢博主您的回复

**Comment by pengfeiw** [comment]
> 

当然可以边做边学，canvas 这种教程，花个**半天时间**大致了解下怎么去绘制一根线段，怎么绘制一个多边形，如何更新画笔的颜色就可以了。然后就可以直接使用canvas去写小游戏了。

**Comment by pengfeiw** [comment]
另外写这种东西，框架不是必须的，只用 html + js + css + canvas，就可以写出来了。我用 vue 也只是回顾下 vue 的使用。

**Comment by shijianzugouniai** [comment]
博主好谦和啊，我已经向我的好朋友都安利博主您的项目了，争取积累起更多的star

**Comment by pengfeiw** [comment]
@shijianzugouniai 感谢😊

**Comment by shijianzugouniai** [comment]
感谢博主您的回答，争取早日将您的项目学懂(我关闭comment啦)
